eureka:
  client:
    serviceUrl:
      defaultZone: http://10.50.16.124:8001/eureka
    registerWithEureka: false

spring:
  datasource:
    invest:
      driverClassName: com.mysql.jdbc.Driver
      username: htf_user_dev
      password: Abc@Htf123456
      url: jdbc:mysql://10.50.115.225:3306/assistant_platform_dev?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=PRC&allowMultiQueries=true&useAffectedRows=true&autoReconnect=true
      timeoutSeconds: 30
    wdb:
      driverClassName: com.mysql.jdbc.Driver
      username: root
      password: 123456789
      url: jdbc:mysql://10.50.115.225:3306/wdb?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=PRC&allowMultiQueries=true&useAffectedRows=true&autoReconnect=true
      timeoutSeconds: 30
    oa:
      driverClassName: oracle.jdbc.driver.OracleDriver
      username: HTF_IRAM
      password: HTF_IRAM#123
      url: jdbc:oracle:thin:@10.50.144.48:1521:uatods
      timeoutSeconds: 30
  redis:
    pool:
      max-idle: 8
      max-active: 8
      max-wait: 1000
    host: 10.50.115.225
    port: 6379
    password:
    database: 1
    timeout: 1000