eureka:
  client:
    serviceUrl:
      defaultZone: http://10.50.16.124:8001/eureka

spring:
  datasource:
    invest:
      driverClassName: com.mysql.jdbc.Driver
      username: abcin_sys_rw_pe
      password: 68hjHEDOjPFb
      url: jdbc:mysql://100.114.151.37:6633/abc_investnew?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
      timeoutSeconds: 30
  redis:
    pool:
      max-idle: 8
      max-active: 8
      max-wait: 1000
    host: 10.81.88.218
    port: 8813
    password: c1YAbuAZjN7o
    database: 1
    timeout: 1000